

- hosts: all
  tasks:
 
   - name: create a docker image
     command: docker build -t tomcat .
     args:
      chdir: /opt/docker
      
   
     
   - name: push the image to docker hub
     command: docker push bharath654/ansible
 
     

     
