

- hosts: all
  tasks: 
   - name: create a docker image
     command: docker build -t tomcat .
     args:
      chdir: /opt/docker

   - name: create a tag for image
     docker_image:
      name: "tomcat:latest"
      repository: "bharath654/ansible:latest"

   - name: push into dockerhubb
     docker_image:
      name: "bharath654/ansible:latest"
      push: yes
      
