

- hosts: all
  tasks: 
   - name: create a docker image
     command: docker build -t tomcat .
     args:
      chdir: /opt/docker
   - name: create a tagname for image
     command: docker tag tomcat:latest bharath654/ansible:latest
     
   - name: push the  image to docker hub
     command: docker push bharath654/ansible:latest

     
