

- hosts: all
  tasks: 
  become: true
   - name: create a docker image
     command: docker build -t tomcat .
     args:
      chdir: /opt/docker
      
   - name: create a tagname for image
     docker_image:
      name: "tomcat:latest"
      repository: "bharath654/ansible:latest"
     
   - name: push the image to docker hub
     docker_image: 
      name: "bharath654/ansible:latest
      push: yes
     

     
